imports:
    - { resource: "container/components.yml" }
    - { resource: "container/controllers.yml" }
    - { resource: "container/serializer.yml" }
    - { resource: "container/devtools.yml" }
    - { resource: "container/listeners.yml" }
    - { resource: "container/forms.yml" }
    - { resource: "container/presentation.yml" }
    - { resource: "container/aliases.yml" }

services:
    app.manager.email:
        class: AppBundle\Manager\EMailManager
        lazy: true
        arguments:
            - "@twig"
            - "@mailer"
            - "%app.email.sender%"
            - "%app_name%"

