services:

    app.presenter:
        class: AppBundle\Presentation\TwigPresenter
        arguments:
            - "@twig"


    app.flash:
        class: AppBundle\Presentation\ResultFlashBuilder
        arguments:
            - "@session.flash_bag"
            - "@translator"